### ISSUE TITLE
Translation to brazilian portuguese plus suggestion

### ISSUE THREAD

**Issue by Felipefpl** [gid15/jpcsp#380]
Hi, here is the link to my updated translation http://www.4shared.com/archive/iE86bQ9nba/Brazilian_Portuguese_Jpcsp_373.html

I wanna suggest this: put all the links related to Jpcsp on top of the page to give them more visibility just like it's done here https://github.com/OtterBrowser/otter-browser the link is on top and everyone see it. ;)

**Comment by gid15** [comment]
I can't download from there without having to register first. Could you upload the file on a site not requiring a registration?

Thank you

**Comment by Felipefpl** [comment]
Sorry about that, i didnt know 4shared started to force registration upon ppl who wants to download the files there, it wasnt like that before... :/ i need to find a new place where i can send my stuff that is similar to them, here is the file http://ge.tt/api/1/files/9ISvtCE2/0/blob?download

**Comment by gid15** [comment]
Great! Thank you
